project:
  title: "Wdrażanie modeli uczenia maszynowego"
  output-dir: docs
  type: website

website:
  title: "Wdrażanie modeli uczenia maszynowego"
  page-footer: "Copyright 2024, Dariusz Majerek"
  sidebar:
    style: "docked"
    background: warning
    search: true
    border: true
    tools: 
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/dax44/ModelsDeployment
          - text: Report a Bug
            url:  https://github.com/dax44/ModelsDeployment/issues
    contents:
      - index.qmd
      - wyk1.qmd
      - wyk2.qmd
      - wyk3.qmd
      - wyk4.qmd
      - wyk5.qmd
      - wyk6.qmd
      - wyk7.qmd
    
format:
  html:
    reference-location: margin
    crossref: 
      fig-title: Rys.     # (default is "Figure")
      tbl-title: Tab.     # (default is "Table")
      fig-prefix: Rys.
      tbl-prefix: Tab.
    grid:
      sidebar-width: 300px
      body-width: 1400px
      margin-width: 300px
      gutter-width: 1.5rem
    lang: pl
    theme:
      light: [flatly, mycss.scss]
      dark: [darkly, mycss.scss]
    code-link: true
    code-fold: show
    fig-align: center

execute: 
  warning: false

editor: visual
